give @s karasichek:bocal_empty
give @s karasichek:chienese_kamelia
give @s karasichek:clay_cup
give @s karasichek:coffee
give @s karasichek:coffee_beans
give @s karasichek:coffee_crop
give @s karasichek:coffee_cup
give @s karasichek:coffee_latte
give @s karasichek:coffee_mokko
give @s karasichek:cup
give @s karasichek:glowberry_custard
give @s karasichek:green_tea_cold
give @s karasichek:green_tea_hot
give @s karasichek:green_tea_lemon
give @s karasichek:kamelia_crop
give @s karasichek:kettle
give @s karasichek:lavender
give @s karasichek:lavender_crop
give @s karasichek:lavender_te_cold
give @s karasichek:lemon
give @s karasichek:lemon_leaves
give @s karasichek:lemon_llog
give @s karasichek:lemon_planks
give @s karasichek:lime
give @s karasichek:matcha_tea
give @s karasichek:lemon_sapling
give @s karasichek:lemon_log
give @s karasichek:oolong
give @s karasichek:oolong_tea
give @s karasichek:tea_black_cold
give @s karasichek:tea_black_hot
give @s karasichek:tea_black_lemon
give @s karasichek:tea_bag_block
give @s karasichek:tea_leaves
